### ISSUE TITLE
ssr-manifest.json should be stored in dist/server

### ISSUE THREAD

**Issue by IlyaSemenov** [frandiox/vite-ssr#20]
I believe `ssr-manifest.json` is logically a server dependency and thus should rather be stored in `dist/server`.

Let's say I want to deploy a SSR server as a micro-service (and publish assets at CDN).
For the micro-service, I will need the entire `dist/server` folder and for some reason one file from `client` (which is not used by the client itself). How so?

**Comment by frandiox** [comment]
@IlyaSemenov Yeah I thought the same. The thing is that the `ssr-manifest.json` is created by the Vite non-SSR build. That's why is written to `dist/client` with all the other non-SSR assets: https://vitejs.dev/guide/ssr.html#generating-preload-directives

I guess it's possible to copy it to the `dist/server/` directory after both builds are done 🤔

**Comment by IlyaSemenov** [comment]
I see. If Vite wants it this way it probably makes sense to keep it as is (or discuss upstream).
