### ISSUE TITLE
Example not work

### ISSUE THREAD

**Issue by ariran5** [frandiox/vite-ssr#3]
Hi, i download this project with example and i try start this. After start  he say me "Error: Cannot find module 'vite-ssr/build'"

nodejs 15.4

**Comment by frandiox** [comment]
@ariran5 Hi! I can't reproduce this. I did a fresh git clone > `cd example` > `yarn` > `yarn build` > `yarn serve:node` and it works as expected with Node 15 🤔 

Are you using Windows?
Can you try modifying the `vite-ssr` dependency line in `example/package.json` and use version `"*"` instead of the local path?
