### ISSUE TITLE
initialState adds unnecessary attributes. Extraneous non-props attributes warning.

### ISSUE THREAD

**Issue by mvrlin** [frandiox/vite-ssr#98]
Hey! Thank you for the great SSR solution! I have an issue with the `initialState`: when I pass something inside, it adds attributes to the component.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/24970784/132983569-53d5a22e-c136-417f-94cd-7ec992bcbf21.png">

The issue resolves by adding a wrapper to the page, but it adds unnecessary attributes 😢
Is there any solution to that?

<img width="634" alt="image" src="https://user-images.githubusercontent.com/24970784/132983547-7248e2a3-71c3-4304-bab6-a241ac92b6ee.png">

**P.S I tested your Vue example and got the same warn.**
<img width="887" alt="image" src="https://user-images.githubusercontent.com/24970784/132983627-bcb4d827-14a8-4984-85fe-cf787a020b0c.png">

**Comment by frandiox** [comment]
@mvrlin Hi there, glad you liked it!

I would say this is somewhat expected because the initialState is basically passed to your page component as props.
Therefore, you can declare every prop in your component (`props.viewport` in your case) so Vue knows what to do with them instead of rendering them as HTML attributes.

Alternatively, if you don't want to rely on props at all, you can pass `{ routes, pageProps: { passToPage: false } }` to Vite SSR (you would need to get the initialState using `useContext` instead). The reason you can see the warning in the repo example is because I'm using two different approaches (props + context) just to test things out. I should update the example to wrap everything in a div 😅 

Does that make sense?

**Comment by mvrlin** [comment]
@frandiox Thanks! Yes, that solves the problem!
